inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.8

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "./spec/**/*"
