name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: bundle exec rake
